language: go

go:
- "1.14.x"

install:
- go mod vendor

script:
- go test ./...

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
